export const JOB_POOL = [
  {
    company: "Stripe",
    logo: "S",
    role: "Frontend Engineer",
    location: "Remote (EU)",
    salary: "€85–120k",
    tags: ["React", "TypeScript", "Next.js", "Performance"],
    type: "Full-time",
  },
  {
    company: "Linear",
    logo: "L",
    role: "Senior Frontend Engineer",
    location: "Remote",
    salary: "$140–180k",
    tags: ["React", "TypeScript", "GraphQL", "System Design"],
    type: "Full-time",
  },
  {
    company: "Vercel",
    logo: "V",
    role: "Full Stack Engineer",
    location: "Berlin",
    salary: "€95–130k",
    tags: ["Next.js", "Node.js", "TypeScript", "Edge"],
    type: "Full-time",
  },
  {
    company: "Datadog",
    logo: "D",
    role: "Backend Engineer",
    location: "Paris",
    salary: "€80–110k",
    tags: ["Node.js", "PostgreSQL", "AWS", "Docker"],
    type: "Full-time",
  },
  {
    company: "Shopify",
    logo: "Sh",
    role: "Senior Frontend Engineer",
    location: "Remote",
    salary: "$150–190k",
    tags: ["React", "TypeScript", "Performance", "Accessibility"],
    type: "Full-time",
  },
  {
    company: "Spotify",
    logo: "Sp",
    role: "Data Scientist",
    location: "Stockholm",
    salary: "€75–105k",
    tags: ["Python", "SQL", "Machine Learning", "A/B Testing"],
    type: "Full-time",
  },
  {
    company: "Airbnb",
    logo: "A",
    role: "Full Stack Engineer",
    location: "Remote",
    salary: "$140–180k",
    tags: ["React", "Node.js", "TypeScript", "PostgreSQL"],
    type: "Full-time",
  },
  {
    company: "GitHub",
    logo: "G",
    role: "DevOps Engineer",
    location: "Remote",
    salary: "$130–170k",
    tags: ["Docker", "Kubernetes", "AWS", "Terraform"],
    type: "Full-time",
  },
  {
    company: "Cloudflare",
    logo: "C",
    role: "Cloud Engineer",
    location: "Lisbon",
    salary: "€70–100k",
    tags: ["AWS", "Terraform", "Kubernetes", "Linux"],
    type: "Full-time",
  },
  {
    company: "OpenAI",
    logo: "O",
    role: "Machine Learning Engineer",
    location: "San Francisco",
    salary: "$200–280k",
    tags: ["Python", "PyTorch", "MLOps", "AWS"],
    type: "Full-time",
  },
  {
    company: "Siemens",
    logo: "Si",
    role: "Mechanical Engineer",
    location: "Munich",
    salary: "€55–75k",
    tags: ["SolidWorks", "AutoCAD", "Thermodynamics", "Manufacturing"],
    type: "Full-time",
  },
  {
    company: "Bechtel",
    logo: "B",
    role: "Civil Engineer",
    location: "Dubai",
    salary: "$60–85k",
    tags: ["AutoCAD", "Revit", "Structural Analysis", "Project Management"],
    type: "Full-time",
  },
  {
    company: "Tesla",
    logo: "T",
    role: "Electrical Engineer",
    location: "Berlin",
    salary: "€70–95k",
    tags: ["Circuit Design", "PCB Design", "MATLAB", "Power Systems"],
    type: "Full-time",
  },
  {
    company: "BASF",
    logo: "Ba",
    role: "Chemical Engineer",
    location: "Ludwigshafen",
    salary: "€60–85k",
    tags: ["Aspen Plus", "Process Safety", "Thermodynamics", "HAZOP"],
    type: "Full-time",
  },
  {
    company: "Toyota",
    logo: "Ty",
    role: "Automotive Engineer",
    location: "Nagoya",
    salary: "¥6–9M",
    tags: ["CATIA", "Vehicle Dynamics", "MATLAB", "Powertrain"],
    type: "Full-time",
  },
  {
    company: "Foster + Partners",
    logo: "F+",
    role: "Architect",
    location: "London",
    salary: "£45–65k",
    tags: ["Revit", "Rhino", "AutoCAD", "Lumion"],
    type: "Full-time",
  },
  {
    company: "Figma",
    logo: "F",
    role: "Product Designer",
    location: "London",
    salary: "£70–95k",
    tags: ["Figma", "Design Systems", "Prototyping", "User Research"],
    type: "Full-time",
  },
  {
    company: "Pentagram",
    logo: "Pe",
    role: "Graphic Designer",
    location: "New York",
    salary: "$70–95k",
    tags: ["Adobe Illustrator", "Adobe Photoshop", "Typography", "Branding"],
    type: "Full-time",
  },
  {
    company: "Notion",
    logo: "N",
    role: "Product Manager",
    location: "New York",
    salary: "$160–210k",
    tags: ["Roadmapping", "Analytics", "User Research", "SQL"],
    type: "Full-time",
  },
  {
    company: "McKinsey",
    logo: "Mk",
    role: "Business Analyst",
    location: "London",
    salary: "£55–80k",
    tags: ["Excel", "PowerPoint", "SQL", "Problem Solving"],
    type: "Full-time",
  },
  {
    company: "HubSpot",
    logo: "Hs",
    role: "Marketing Manager",
    location: "Dublin",
    salary: "€65–90k",
    tags: ["SEO", "Google Analytics", "Content Strategy", "HubSpot"],
    type: "Full-time",
  },
  {
    company: "Salesforce",
    logo: "Sf",
    role: "Sales Executive",
    location: "Remote",
    salary: "$90–140k OTE",
    tags: ["CRM (Salesforce)", "Cold Outreach", "Negotiation", "Pipeline Management"],
    type: "Full-time",
  },
  {
    company: "Goldman Sachs",
    logo: "GS",
    role: "Financial Analyst",
    location: "London",
    salary: "£60–85k",
    tags: ["Excel", "Financial Modeling", "Valuation", "PowerPoint"],
    type: "Full-time",
  },
  {
    company: "Deloitte",
    logo: "De",
    role: "Consultant",
    location: "Madrid",
    salary: "€45–65k",
    tags: ["Excel", "PowerPoint", "Problem Solving", "Market Research"],
    type: "Full-time",
  },
  {
    company: "Unilever",
    logo: "U",
    role: "Operations Manager",
    location: "Rotterdam",
    salary: "€70–95k",
    tags: ["Process Improvement", "KPIs", "Lean", "ERP"],
    type: "Full-time",
  },
  {
    company: "PwC",
    logo: "Pw",
    role: "Human Resources Specialist",
    location: "Berlin",
    salary: "€50–70k",
    tags: ["Recruitment", "Onboarding", "HRIS", "Communication"],
    type: "Full-time",
  },
  {
    company: "MrBeast Studios",
    logo: "MB",
    role: "Content Creator",
    location: "Remote",
    salary: "$60–110k",
    tags: ["Video Editing (Premiere Pro)", "Storytelling", "Social Media Strategy", "Branding"],
    type: "Full-time",
  },
  {
    company: "Buffer",
    logo: "Bf",
    role: "Social Media Manager",
    location: "Remote",
    salary: "$60–85k",
    tags: ["Content Strategy", "Copywriting", "Canva", "Analytics"],
    type: "Full-time",
  },
  {
    company: "Netflix",
    logo: "Nf",
    role: "Video Editor",
    location: "Los Angeles",
    salary: "$80–120k",
    tags: ["Premiere Pro", "DaVinci Resolve", "Color Grading", "Storytelling"],
    type: "Full-time",
  },
  {
    company: "Medium",
    logo: "Md",
    role: "Copywriter",
    location: "Remote",
    salary: "$55–85k",
    tags: ["Copywriting", "SEO", "Editing", "Brand Voice"],
    type: "Full-time",
  },
  {
    company: "Vodafone Egypt",
    logo: "VE",
    role: "Frontend Engineer",
    location: "Cairo, Egypt",
    salary: "EGP 25–40k/mo",
    tags: ["React", "TypeScript", "JavaScript", "Tailwind CSS", "Git"],
    type: "Full-time",
  },
  {
    company: "Fawry",
    logo: "Fw",
    role: "Backend Engineer",
    location: "Cairo, Egypt",
    salary: "EGP 30–45k/mo",
    tags: ["Node.js", "PostgreSQL", "REST APIs", "Docker", "AWS"],
    type: "Full-time",
  },
  {
    company: "Paymob",
    logo: "Pm",
    role: "Full Stack Engineer",
    location: "Cairo, Egypt",
    salary: "EGP 28–42k/mo",
    tags: ["React", "Node.js", "TypeScript", "PostgreSQL"],
    type: "Full-time",
  },
  {
    company: "Swvl",
    logo: "Sw",
    role: "Mobile Developer",
    location: "Cairo, Egypt",
    salary: "EGP 22–38k/mo",
    tags: ["React Native", "Kotlin", "REST APIs", "Firebase"],
    type: "Full-time",
  },
  {
    company: "Instabug",
    logo: "Ib",
    role: "Senior Frontend Engineer",
    location: "Cairo / Remote",
    salary: "EGP 35–55k/mo",
    tags: ["React", "TypeScript", "Performance", "Testing (Jest)"],
    type: "Full-time",
  },
  {
    company: "Raya",
    logo: "Ry",
    role: "Business Analyst",
    location: "Cairo, Egypt",
    salary: "EGP 18–28k/mo",
    tags: ["SQL", "Excel", "Requirements Gathering", "Documentation"],
    type: "Full-time",
  },
  {
    company: "Commercial International Bank",
    logo: "CIB",
    role: "Financial Analyst",
    location: "Cairo, Egypt",
    salary: "EGP 20–32k/mo",
    tags: ["Excel", "Financial Modeling", "Accounting", "PowerPoint"],
    type: "Full-time",
  },
  {
    company: "Orascom Construction",
    logo: "OC",
    role: "Civil Engineer",
    location: "Cairo, Egypt",
    salary: "EGP 15–25k/mo",
    tags: ["AutoCAD", "Project Management", "Structural Analysis", "Surveying"],
    type: "Full-time",
  },
  {
    company: "Elaraby Group",
    logo: "EA",
    role: "Mechanical Engineer",
    location: "Monufia, Egypt",
    salary: "EGP 12–20k/mo",
    tags: ["AutoCAD", "SolidWorks", "Manufacturing", "Thermodynamics"],
    type: "Full-time",
  },
  {
    company: "Sadat Academy",
    logo: "SA",
    role: "Marketing Manager",
    location: "Menofia, Egypt",
    salary: "EGP 14–22k/mo",
    tags: ["SEO", "Content Strategy", "Social Media", "Google Analytics"],
    type: "Full-time",
  },
] as const;
