import type { JobListing } from "./jobs-types";

/** Additional roles across every industry — merged with main job pool. */
export const EXTRA_JOB_LISTINGS: JobListing[] = [
  {
    company: "Uber",
    logo: "U",
    role: "Delivery Driver",
    location: "Cairo, Egypt",
    salary: "EGP 8–15k/mo + tips",
    tags: ["Driving License", "GPS Navigation", "Customer Service", "Time Management"],
    type: "Flexible",
    category: "transport",
    applyUrl: "https://www.linkedin.com/jobs/search/?keywords=delivery%20driver%20cairo",
    source: "linkedin",
  },
  {
    company: "Amazon Logistics",
    logo: "Am",
    role: "Truck Driver",
    location: "6th October, Egypt",
    salary: "EGP 12–18k/mo",
    tags: ["CDL", "Route Planning", "Vehicle Inspection", "Safety Compliance"],
    type: "Full-time",
    category: "transport",
    applyUrl: "https://www.linkedin.com/jobs/search/?keywords=truck%20driver%20egypt",
    source: "linkedin",
  },
  {
    company: "Go Bus",
    logo: "GB",
    role: "Bus Driver",
    location: "Alexandria, Egypt",
    salary: "EGP 10–14k/mo",
    tags: ["Driving License", "Passenger Safety", "Route Knowledge", "First Aid"],
    type: "Full-time",
    category: "transport",
  },
  {
    company: "EgyptAir",
    logo: "EA",
    role: "Commercial Pilot",
    location: "Cairo, Egypt",
    salary: "EGP 45–90k/mo",
    tags: ["ATPL", "IFR", "Crew Resource Management", "English Proficiency", "Flight Planning"],
    type: "Full-time",
    category: "aviation",
    applyUrl: "https://www.linkedin.com/jobs/search/?keywords=pilot%20egypt",
    source: "linkedin",
  },
  {
    company: "Air Arabia",
    logo: "AA",
    role: "Flight Attendant",
    location: "Cairo / Remote bases",
    salary: "EGP 15–25k/mo",
    tags: ["Customer Service", "Safety Procedures", "First Aid", "Arabic", "English"],
    type: "Full-time",
    category: "aviation",
  },
  {
    company: "Teleperformance Egypt",
    logo: "TP",
    role: "Call Center Agent",
    location: "Smart Village, Egypt",
    salary: "EGP 8–14k/mo",
    tags: ["Communication", "CRM", "Active Listening", "English", "Typing Speed"],
    type: "Full-time",
    category: "customer_service",
    applyUrl: "https://www.linkedin.com/jobs/search/?keywords=call%20center%20cairo",
    source: "linkedin",
  },
  {
    company: "Vodafone Contact Center",
    logo: "VC",
    role: "Customer Support Specialist",
    location: "Cairo, Egypt",
    salary: "EGP 9–16k/mo",
    tags: ["Customer Service", "Problem Solving", "Arabic", "English", "Zendesk"],
    type: "Full-time",
    category: "customer_service",
  },
  {
    company: "Marriott",
    logo: "M",
    role: "Front Desk Agent",
    location: "Sharm El Sheikh, Egypt",
    salary: "EGP 7–12k/mo",
    tags: ["Hospitality", "Communication", "Opera PMS", "English", "Customer Service"],
    type: "Full-time",
    category: "hospitality",
  },
  {
    company: "Talabat",
    logo: "Tb",
    role: "Restaurant Captain",
    location: "Giza, Egypt",
    salary: "EGP 6–10k/mo",
    tags: ["Team Leadership", "POS Systems", "Customer Service", "Food Safety"],
    type: "Full-time",
    category: "hospitality",
  },
  {
    company: "Cleopatra Hospital",
    logo: "CH",
    role: "Registered Nurse",
    location: "Cairo, Egypt",
    salary: "EGP 10–18k/mo",
    tags: ["Patient Care", "BLS", "Medical Records", "Communication", "Empathy"],
    type: "Full-time",
    category: "healthcare",
  },
  {
    company: "57357 Hospital",
    logo: "57",
    role: "Pharmacist",
    location: "Cairo, Egypt",
    salary: "EGP 12–20k/mo",
    tags: ["Pharmacology", "Inventory", "Patient Counseling", "Regulations"],
    type: "Full-time",
    category: "healthcare",
  },
  {
    company: "Orascom",
    logo: "Or",
    role: "Electrician",
    location: "New Cairo, Egypt",
    salary: "EGP 8–15k/mo",
    tags: ["Wiring", "Safety Codes", "Blueprint Reading", "Troubleshooting"],
    type: "Full-time",
    category: "trades",
  },
  {
    company: "SODIC",
    logo: "So",
    role: "Plumber",
    location: "North Coast, Egypt",
    salary: "EGP 7–13k/mo",
    tags: ["Pipefitting", "Installation", "Maintenance", "Safety"],
    type: "Contract",
    category: "trades",
  },
  {
    company: "Carrefour Egypt",
    logo: "Cf",
    role: "Cashier",
    location: "Mansoura, Egypt",
    salary: "EGP 5–8k/mo",
    tags: ["POS", "Cash Handling", "Customer Service", "Accuracy"],
    type: "Part-time",
    category: "retail",
  },
  {
    company: "Zara",
    logo: "Z",
    role: "Sales Associate",
    location: "Cairo, Egypt",
    salary: "EGP 6–10k/mo",
    tags: ["Retail Sales", "Visual Merchandising", "Communication", "Inventory"],
    type: "Full-time",
    category: "retail",
  },
  {
    company: "G4S Egypt",
    logo: "G4",
    role: "Security Guard",
    location: "Cairo, Egypt",
    salary: "EGP 6–9k/mo",
    tags: ["Surveillance", "Access Control", "Report Writing", "Physical Fitness"],
    type: "Full-time",
    category: "security",
  },
  {
    company: "Juhayna",
    logo: "Jh",
    role: "Warehouse Operator",
    location: "10th of Ramadan, Egypt",
    salary: "EGP 7–11k/mo",
    tags: ["Forklift", "Inventory", "Safety", "Teamwork"],
    type: "Full-time",
    category: "manufacturing",
  },
  {
    company: "EF Education",
    logo: "EF",
    role: "English Teacher",
    location: "Cairo, Egypt",
    salary: "EGP 12–22k/mo",
    tags: ["TESOL", "Lesson Planning", "Communication", "Classroom Management"],
    type: "Full-time",
    category: "education",
  },
  {
    company: "Ministry of Education",
    logo: "MoE",
    role: "School Teacher",
    location: "Menofia, Egypt",
    salary: "EGP 8–14k/mo",
    tags: ["Curriculum", "Assessment", "Classroom Management", "Communication"],
    type: "Full-time",
    category: "education",
  },
  {
    company: "NBE",
    logo: "NBE",
    role: "Bank Teller",
    location: "Tanta, Egypt",
    salary: "EGP 9–14k/mo",
    tags: ["Cash Handling", "Customer Service", "Compliance", "Arabic", "English"],
    type: "Full-time",
    category: "finance",
  },
  {
    company: "Arab Contractors",
    logo: "AC",
    role: "Site Engineer",
    location: "New Capital, Egypt",
    salary: "EGP 14–22k/mo",
    tags: ["AutoCAD", "Project Management", "Site Supervision", "Safety"],
    type: "Full-time",
    category: "engineering",
  },
  {
    company: "Nile TV",
    logo: "NT",
    role: "Video Editor",
    location: "Cairo, Egypt",
    salary: "EGP 10–18k/mo",
    tags: ["Premiere Pro", "After Effects", "Storytelling", "Color Grading"],
    type: "Full-time",
    category: "creative",
  },
  {
    company: "Siemens Egypt",
    logo: "Si",
    role: "Maintenance Technician",
    location: "Suez, Egypt",
    salary: "EGP 11–17k/mo",
    tags: ["Mechanical", "Electrical", "Troubleshooting", "Safety"],
    type: "Full-time",
    category: "manufacturing",
  },
  {
    company: "Maersk",
    logo: "Mk",
    role: "Logistics Coordinator",
    location: "Port Said, Egypt",
    salary: "EGP 12–20k/mo",
    tags: ["Supply Chain", "Documentation", "Excel", "Communication"],
    type: "Full-time",
    category: "transport",
  },
  {
    company: "Etisalat",
    logo: "Et",
    role: "Field Sales Representative",
    location: "Assiut, Egypt",
    salary: "EGP 8–15k/mo + commission",
    tags: ["Sales", "Negotiation", "CRM", "Communication", "Driving License"],
    type: "Full-time",
    category: "retail",
  },
];
